  <div id="main-menu-controller" class="navigation show-phone">
	  	<ul class="links clearfix">
	  		<li id="prefix-display-button"><a href="#"><img src="/sites/all/themes/custom/unity/stylesheets/images/menu-text.png"></a></li>
	  	</ul>
	  </div>

      <div id="main-menu-navigation" class="navigation hide-phone">
      	<ul id="main-menu-links" class="links clearfix">
			<li class="menu-876 first active"><a href="/" title="Home" class="active">Home</a></li>
			<li class="menu-527"><a href="/services/catalog/a-z/all" title="">Services</a></li>
			<li class="menu-2225"><a href="/projects" title="">Projects</a></li>
			<li class="menu-560 last"><a href="/help" title="">Help</a></li>
		</ul>
      </div> <!-- /#main-menu -->
	  <div id="search-wrapper" class="search show-desktop">
	  	<span id="search-label" class="">SEARCH SITE:</span><input type="text" class="search-box"/> <input class="search-go" type="submit" value="Go">
	  </div>
 	  <div id="search-controller" class="navigation show-phone">
	  	<ul class="links clearfix">
	  		<li id="search-controller-button"><a href="#"><img src="/sites/all/themes/custom/unity/stylesheets/images/search-text.png"></a></li>
	  	</ul>
	  </div>	